apps/app/lib/track.ts, apps/app/middleware.ts
fixed issue in middleware requiring auth for mixpanelf
=> Mixpanel Tracking Resolution

apps/app/app/explore/page.tsx, apps/app/components/playground/form.tsx, apps/app/components/playground/output.tsx, apps/app/components/playground/try.tsx, apps/app/components/sidebar.tsx, apps/app/components/welcome/featured/index.tsx, packages/design-system/components/ui/sidebar.tsx
- update playground page
- update landing page
- add sidebar hover effect
=> ui: minor ui updates and fixes

apps/app/app/api/streams/webhook/route.ts
return stream_id in webhook response
=> webhook: return stream_id and pipeline_id

apps/docs/mint.json
Removes the api reference section from the sidebar
=> removed api reference

apps/app/app/explore/page.tsx, apps/app/components/header/alpha-banner.tsx, apps/app/components/playground/output.tsx, apps/app/components/playground/try.tsx, apps/app/components/sidebar.tsx, apps/app/components/welcome/featured/index.tsx, apps/app/components/welcome/index.tsx
Also removed non-comfyUI option from filter view and moved Pipelines above Streams in the UI
=> Copy changes (marketing review)

apps/docs/mint.json, apps/docs/technical/reference/local-testing-comfystream-ui.mdx, apps/docs/technical/reference/local-testing-comfyuilauncher.mdx, apps/docs/technical/reference/local-testing.mdx
This change adds a local development guides for comfyui node development
=> add local dev guides

apps/app/app/api/streams/get.ts, apps/app/app/page.tsx, apps/app/components/playground/try.tsx, apps/app/components/stream/stream-form.tsx, apps/app/lib/env.ts, apps/app/lib/serverEnv.ts, packages/supabase/admin.ts, packages/supabase/client.ts, packages/supabase/index.ts, packages/supabase/server.ts
Separate out supabase from env into secured serverEnv, add gateway_host fields to stream get ops, and update stream form to render any object types as json in textarea
TO DEPLOY - remove NEXT_PUBLIC from all NEXT_PUBLIC_SUPABASE_* props.
=> Secure Supabase Creds and Fix Stream Form for Comfy Streams

apps/docs/knowledge-base/get-started/create-your-first-pipeline.mdx, apps/docs/mint.json, apps/docs/technical/develop-pipeline/create-your-first-pipeline.mdx, apps/docs/technical/reference/available-nodes.mdx, apps/docs/technical/reference/develop-runpod.mdx, apps/docs/technical/reference/local-testing-comfyuilauncher.mdx, apps/docs/technical/reference/local-testing.mdx, apps/docs/technical/reference/performance-recommendations.mdx
- Adds steps for Run Pod setup
- Updates the blank "Create your first pipeline" with an introduction and links to guides
- Adds detail to performance recommendations
- Small formatting fixes
=> Add RunPod setup instructions

apps/docs/technical/reference/available-nodes.mdx
- Updates the list of default nodes that come with ComfyUI
- Adds `ComfyUI-load-image-from-url Node` to custom nodes list
=> Update layout for available-nodes

apps/app/components/playground/try.tsx
Attempt at fixing empty pipeline_params
=> pipelines: fix empty pipeline_params

apps/docs/mint.json, apps/docs/technical/develop-pipeline/add-sd-loras.mdx
Adds a new article "Customizing Stable Diffusion LoRas" which provides an overview of how to define the LoRa checkpoint and SD Model checkpoints for a comfyui workflow
=> Add stable diffusion LoRa doc

apps/app/app/api/streams/[id]/status/route.ts, apps/app/app/streams/my-streams/page.tsx, apps/app/components/stream/stream-form.tsx, apps/app/lib/serverEnv.ts
Fix dark mode rendering of stream pipeline params, leverage gateway_host in stream status api, move status configs to serverEnv.ts, and clean up stream form to remove dependency on hardcoded field ids for json inputs.
=> Add gateway host to status, clean up json handling, dark mode fix

apps/app/components/header/action.ts
At the moment this is failing in some cases and it isn't clear why
=> Log the error when user creation fails

apps/app/components/playground/try.tsx
- Fix key value on params update
=> fix: undefined json on parse params update

apps/app/app/explore/page.tsx, apps/app/components/welcome/featured/index.tsx, apps/docs/knowledge-base/get-started/what-is-pipeline.mdx, apps/docs/technical/develop-pipeline/what-is-pipeline.mdx
@hthillman I manually reapplied your marketing vid changes here
=> Updating videos from marketing

apps/app/app/stream/[id]/page.tsx, apps/app/components/stream/stream-form.tsx
- Fix missing primary field for non-comfy pipelines
- Add saving indicators to stream form submit button
=> Fix non-comfy stream save and add saving indicator to button

apps/app/app/stream/[id]/page.tsx, apps/app/components/stream/stream-form.tsx
- Add saving indicators to stream form submit button
=> Deploy to Prod

apps/docs/technical/reference/available-nodes.mdx, apps/docs/technical/reference/develop-runpod.mdx, apps/docs/technical/reference/local-testing-comfystream-ui.mdx
- Add runpod template
- Add TensorRT node info
- Improve "How to stop a RunPod Server"
=> Add runpod template, tensorrt node info

apps/docs/technical/develop-pipeline/create-your-first-pipeline.mdx, apps/docs/technical/install/local-testing.mdx
Fix some typos and simply bash commands
=> doc improvements

apps/docs/technical/install/local-testing.mdx
Fixes path to clone install scripts
=> fix clone path

apps/app/app/api/pipelines/create.ts
- Create a helper to add a wrapper around uploaded comfyui JSONs
=> pipeline: comfyui json helper

apps/app/components/pipeline/create-pipeline.tsx, apps/app/components/pipeline/pipeline-params-selector.tsx
- Frontend for parameter selection on create pipeline (step 2)
Not hooked to any api save yet
=> pipelines: show parameter selection on pipeline creation

apps/app/app/api/pipelines/create.ts, apps/app/app/api/pipelines/edit.ts, apps/app/components/helpers/merkle.tsx, apps/app/components/pipeline/edit-pipeline.tsx, apps/app/components/pipeline/pipeline-params-selector.tsx, apps/app/components/pipeline/validate-pipeline.tsx, apps/app/components/playground/try.tsx, apps/app/components/stream/comfyui-param-editor.tsx, apps/app/lib/types.ts
- Created new field `prioritized_params` in the pipeliene schema
- Storing the chosen params in the field
- Retrieving them on the edit page
- Make sure the edit page uses the `defaultValue` field when displaying the JSON
- Display the existing prioritized_params in the edit page step 2
- Added some merkle function for later use for updating single fields in the JSON (not sure if needed, but they are there for now)
- Widgets
=> pipelines: store prioritized params

apps/app/app/api/pipelines/validation.ts, apps/app/components/pipeline/pipeline-card.tsx, apps/app/components/pipeline/pipeline-params-selector.tsx
- Better UI for param selector
- Avoid triggering smoke tests when on local dev instance
=> feat: pipelines: better param selector & skip smoke test on dev

apps/app/components/header/fetchPipelines.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
- Added fix to filter the `getPipelines` results based on `is_featured: true` flag
- Added support for switching camera using Livepeer controls library
=> bugfix: show only feature pipelines, allow camera change for broadcast

apps/app/app/api/pipelines/validation.ts, apps/app/components/pipeline/pipeline-card.tsx, apps/app/components/pipeline/pipeline-params-selector.tsx
- Fix dropdown params on creation
- Allow to create a pipeline without any suggested param
=> pipelines: allow 0 params on create pipeline

apps/app/app/page.tsx, apps/app/components/modals/trial-expired-modal.tsx, apps/app/components/playground/try.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/interstitial.tsx, apps/app/hooks/useTrialTimer.ts
- 10 minutes trial for unauthenticated users
- CTA to sign up
- CTA to join community
- Track timer usage also in playground pipelines
- Show modal there as well
=> pipelines: landing-page: 10 minutes trial

apps/app/components/playground/try.tsx, apps/app/components/welcome/featured/interstitial.tsx, apps/app/hooks/useStreamStatus.ts
- Added debug view on the playground for admins
=> playground: debug view

.gitignore, apps/docs/mint.json, apps/docs/technical/reference/advanced-node-usage.mdx
This PR adds documentation on advanced node usage, focusing on RealtimeNodes.
=> docs: advanced node usage

apps/app/app/page.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/useDreamshaper.tsx, apps/app/hooks/useTrialTimer.ts
- Moved input prompt on bottom (for later to be changed)
- Made broadcast component fill the container nicely
- made broadcast component draggable and snapping inside the output player container
- Centered title, subtitle
- Minor changes figma based
- Timer indicator
- Live indicator
NOTES:
- Changes to interstitial / loading spinners are going to come in another PR
=> ui: landing: player updates

apps/docs/mint.json
This PR fixes a broken link for the default docs page
=> fix broken link

apps/docs/technical/getting-started/install-comfystream.mdx
This change updates the docker image name in install-comfystream
=> fix docker image name

apps/docs/technical/getting-started/install-comfystream.mdx
Fix an outdated internal mount path for ComfyStream docker run command
=> update internal mount paths

apps/app/app/explore/page.tsx, apps/app/app/layout.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/useDreamshaper.tsx, packages/design-system/components/ui/input.tsx
- Updated the input prompt UI as per designs
- Added actions buttons and layout fixes
- Refactored some UI on Explore Pipelines page - borders/layout issues.
Main Page:
Loading UI:
Mobile View:
=> ui: landing-redesign - refactor input ui, actions buttons

apps/app/app/layout.tsx, apps/app/components/header/sidebar-trigger.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/playground/player.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/interstitial.tsx
- Changed layout of landing page for mobile
- Removed dragging functionality
- Added picture in picture and improved icons
- Improved player display & positioning
=> ui: landing: mobile mode & desktop fixes

apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/package.json, pnpm-lock.yaml
- Added TextAreaAutosize component package that handles the max and min rows and enable scroll if it exceeds maxRows
- Verified on desktop and mobile screens
=> ui: landing redesign - add multiline prompt

apps/app/components/welcome/featured/dreamshaper.tsx
- Just a little change to blur the input prompt on apply on mobile devices, so the keyboard gets dismissed
=> feat: mobile: dismiss keyboard on input apply

apps/app/components/welcome/featured/dreamshaper.tsx
- Better desktop placements & display
=> ui: landing: better desktop display

apps/app/components/welcome/featured/dreamshaper.tsx
- keep last used prompt as placeholder
=> ui: landing: keep last used prompt as placeholder

apps/app/app/page.tsx, apps/app/components/welcome/featured/interstitial.tsx
- Do not skip step 1
- Show again first interstitial if permission of camera is denied, even if the user already visited the page
=> ui: fix: do not auto skip step1

apps/app/components/playground/broadcast.tsx
=> chore: add flip camera button to mobile view

apps/app/.gitignore, apps/app/app/layout.tsx, packages/design-system/providers/theme.tsx
- Added maximum-scale property to handle inputs zooming in on mobile
=> ui: fix - input scales on mobile

apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/useProfanity.tsx, apps/app/components/welcome/featured/utils.ts
- Added logic to validate words while typing
- Display error message with red border when harmful word detected
- Disable the submit button or hotkey actions when harmful detected
=> ui: add profanity filter ux

apps/app/components/welcome/featured/interstitial.tsx
- In some cases, the first step of the interstitial was unskippable even when given camera permissions on mobile
=> ui: fix: fix unskippable step 1 on mobile

apps/app/components/header/user.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
- Fix `Build a pipeline` URL
- Remove toggle theme button
=> chore: fix build-pipeline url, remove theme toggle

apps/app/app/page.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/hooks/useStreamStatus.ts
- Added a max capacity toast adding a capacityReached to useStreamStatus
- Displaying that as well after a 90s timeout
- (temp) shortcut cmd+T to forcefully display it for debug
=> ui: landing: added max capacity toast

apps/app/components/welcome/featured/dreamshaper.tsx
- Just making the broadcast player responsive on desktop
=> ui: landing: responsive broadcast player

apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/interstitial.tsx
- Track mixpanel events for daydream
=> feat: landing: track mixpanel events

apps/app/components/playground/broadcast.tsx, apps/app/package.json, pnpm-lock.yaml
=> bump livepeer/react

apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/interstitial.tsx, apps/app/hooks/useStreamStatus.ts
- Add 2s delay on permission grants
- Add 3s delay on select prompt
=> ui: landing: add modal delays

apps/app/components/modals/trial-expired-modal.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
- Display timer that was hidden behind the player
- Fix waitlist link
- Fix copy text on expire time modal
=> ui: landing: fix copy on expire & timer display

apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/hooks/useStreamStatus.ts
- At capacity only if 5 consecutive gateway error with orch not found
- Display the toast only once
=> ui: fix: capacity toast

apps/app/components/welcome/featured/interstitial.tsx
- Fix modals on smaller screens
=> ui: fix: better modals

apps/app/app/layout.tsx, apps/app/components/sidebar.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
- Fix desktop scroll
- Fix multiline input scroll ui to expand height as the lines increases
- Fix feedback icon based on bugbash, updated to a lightbulb to indicate ideas/feedback
=> chore: ui improvements

apps/app/components/analytics/PageViewTracker.tsx, apps/app/components/analytics/TrackedButton.tsx, apps/app/components/analytics/TrackedInput.tsx, apps/app/components/analytics/TrackedLink.tsx, apps/app/components/analytics/readme.md, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/hooks/useTrack.ts, apps/app/hooks/useTrackButton.ts, apps/app/hooks/useTrackEvent.ts, apps/app/hooks/useTrackInput.ts, apps/app/lib/analytics/event-types.ts
- Added some hooks to enable tracked components
- TrackedButton and TrackedInput, together with PageViewTracker and TrackedLink
- Some generic functions for custom elements
=> daydream: analytics: tracked components

apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
- Enabled Broadcast audio by default for better startup time based on Josh's observations.
https://discord.com/channels/423160867534929930/1344448043470159882/1344448046234079323
=> chore: enable audio for broadcast by default

apps/app/components/header/index.tsx, apps/app/components/modals/trial-expired-modal.tsx, apps/app/components/sidebar.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/index.tsx, apps/app/components/welcome/index.tsx
- Change discord link in daydream
-
=> Change discord link

apps/app/components/welcome/featured/interstitial.tsx, apps/app/components/welcome/featured/slide.tsx, apps/app/lib/utils.ts
- Removed unused hook `useStreamStatus` which is adding unnecessary polling
- Cleanup the code a bit
=> chore: cleanup interstitial, remove unused useStreamStatus hook

apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
This reverts commit e7d31a663d771d314a2987c9bc87c24ab246662b.
=> Revert "chore: enable audio for broadcast by default (#216)"

apps/app/app/api/mixpanel/route.ts, apps/app/components/analytics/MixpanelProvider.tsx, apps/app/components/header/user.tsx, apps/app/components/modals/trial-expired-modal.tsx, apps/app/components/welcome/featured/interstitial.tsx, apps/app/lib/analytics/mixpanel.ts, apps/app/lib/track.ts
1. moved mixpanel util functions to a separate file for reuse in track.ts 
2. added mixpanel user identification to user log-in flow 
3. implemented TrackButton on trial-expired CTAs 
4. refactored track.ts to use re-usable functions
=> Mixpanel Tracking Improvements

apps/app/app/api/mixpanel/route.ts, apps/app/app/api/streams/share-params.ts, apps/app/components/analytics/MixpanelProvider.tsx, apps/app/components/analytics/PageViewTracker.tsx, apps/app/components/analytics/TrackedButton.tsx, apps/app/components/analytics/TrackedInput.tsx, apps/app/components/analytics/TrackedLink.tsx, apps/app/components/daydream/index.tsx, apps/app/components/footer/stream-info.tsx, apps/app/components/modals/trial-expired-modal.tsx, apps/app/components/welcome/featured/ShareModal.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/interstitial.tsx, apps/app/components/welcome/featured/useDreamshaper.tsx, apps/app/hooks/useGatewayHost.ts, apps/app/hooks/useTrack.ts, apps/app/hooks/useTrackButton.ts, apps/app/hooks/useTrackEvent.ts, apps/app/hooks/useTrackInput.ts, apps/app/lib/analytics/event-types.ts, apps/app/lib/analytics/mixpanel.ts, apps/app/lib/generate-id.ts
- Added DB table for share links (NOTE: align prod before merging)
- get / post links api
- Hashing system to avoid duplication
- Share button, aligned new designs
- Share modal
- Pencil edit prompt
- useGatewayHost hook, to be used whenever we need the gateway host to be present to do an action (prompt update, control api, etc)
=> feat: daydream: Shareable parameters

apps/app/components/daydream/index.tsx, apps/app/components/prompting/inputWithCommands.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/prompt-settings.tsx, apps/app/components/welcome/featured/useDreamshaper.tsx, apps/app/hooks/useCommandSuggestions.tsx
- Added param prompting (e.g. "Van Gogh --quality 3 --negative-prompt "My negative prompt")
- Added quality slider
=> feat: daydream: Param command prompting

apps/app/components/welcome/featured/useDreamshaper.tsx
- Fix param parsing when coming from a shared prompt
=> fix: shared prompting

apps/app/components/welcome/featured/useDreamshaper.tsx
Before this, the pipeline object was getting updated on every prompt input, making the parameters persisting. Removing for example a --quality param, it wouldn't reset it to its default value
With this, we refetch the pipeline config from the DB, to make sure any unused params returns to the default state
=> daydream: fix: removed params

apps/app/components/welcome/featured/player.tsx
[To be removed] Added player log
=> chore: add player log

apps/app/components/welcome/featured/dreamshaper.tsx
- change to fixed input placeholder
=> feat: remove rotating placeholder

apps/docs/technical/getting-started/install-comfystream.mdx
Adds prerequisite installation steps for CUDA/WSL and removes command prompt/powershell commands since the docker image is currently built only for linux platforms
=> update windows install

apps/app/components/welcome/featured/useDreamshaper.tsx
- Add versioning for cached params
- Cache is invalidated if the version of the cache is mismatching the version of the pipeline
=> feat: dd: param cache versioning

apps/app/hooks/useVideoClip.ts
- Remove audio because captureStream unsupported by firefox, getting back to it later
=> fix: dd: remove audio from clips

apps/app/components/welcome/featured/player.tsx
- Increase timeout for playback retries
=> feat: increase player timeout

apps/app/app/api/streams/route.ts, apps/app/lib/auth.ts
- Create stream under proper user when an api key is passed as a bearer
- Added auth lib for api key fetch and vlidation
=> feat: dd: api-keys validation & stream creation

apps/app/components/playground/broadcast.tsx
- Remove temporarily audio because issues with output playback in prod
=> temp: fix: remove audio

apps/app/package.json, packages/design-system/package.json, packages/design-system/providers/index.tsx, packages/next-config/package.json, pnpm-lock.yaml
- Unused and causing some build errors in dev. Removed the vercel toolbar and its deps.
=> chore: remove vercel toolbar

apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx
- Align capacity timer with player timer
- Create a retry mechanism for the player when a connect to peer failure happen
=> dd: increase capacity timer + player retries on connection errors

apps/app/components/daydream/LoginScreen/index.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, packages/design-system/styles/globals.css
- Added dynamic gradient border to personas buttons
- Border radius on example video
- Flares on example video
- Repositioned the background to have the blue piece as background behind the white "Transform your video" text
- Line break on Tos and Privacy Policy
=> dd: ui: onboarding visual updates

apps/app/components/daydream/LoginScreen/EmailLoginButton.tsx, apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx
- Updated copy and UI for camera request button
=> chore: fix camera button, sign up copy

apps/app/components/welcome/featured/player.tsx
- Remove unnecessary error log, make it happen only when supposed to
=> dd: fix error log

apps/app/components/ClipButton.tsx, apps/app/components/daydream/LoginScreen/index.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/SelectPrompt.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/hooks/useVideoClip.ts, apps/app/package.json, pnpm-lock.yaml
- Broadcast is now mirrored
- peer connection issues are handled with retires with the package update
=> feat: dd: mirrored broadcast + livepeer react bump

apps/app/components/welcome/featured/player.tsx, apps/app/hooks/useStreamStatus.ts
=> dd: debug: logs for gray screen

apps/app/components/daydream/LayoutWrapper.tsx, apps/app/components/daydream/LoginScreen/EmailLoginButton.tsx, apps/app/components/daydream/LoginScreen/GoogleLoginButton.tsx, apps/app/components/daydream/LoginScreen/index.tsx, apps/app/components/daydream/MainExperience/index.tsx, apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/components/daydream/WelcomeScreen/Footer.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/SelectPrompt.tsx, apps/app/components/daydream/WelcomeScreen/index.tsx, apps/app/components/daydream/index.tsx, apps/app/components/header/user.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/sidebar.tsx, apps/app/components/welcome/featured/ManagedBroadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx, packages/design-system/styles/globals.css
- Updated UI to light theme for the main experience
- Fixed a couple of functional bugs i.e. Terms&Conditions link to open separately, onboarding flow improvements.
=> chore: bugbash UI fixes onboarding flow 

apps/app/components/welcome/featured/player.tsx
=> dd: retry logs

apps/app/components/welcome/featured/dreamshaper.tsx
Eric asked to remove this as part of the onboarding feedback
=> Remove 'Build A Pipeline' link

apps/app/app/api/metrics/kafka.ts, apps/app/lib/track.ts
- Disable analytics env var
- Useful for local and pre-production envs
=> feat: dd: disable analytics env var

apps/app/components/daydream/WelcomeScreen/SelectPrompt.tsx
=> dd: fix: render error

apps/app/components/header/action.ts, apps/app/lib/analytics/hubspot.ts
- `provider` field also includes email provider.
- get email from discord and github provided data
=> feat: improve user creation logic

apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/components/daydream/WelcomeScreen/index.tsx, apps/app/components/header/user.tsx
- Fixed checkmark styles for Camera Access component
- Added padding to the top when user scrolls down to the select prompts view
- Fixed margins on the User Avatar component in sidebar when logged in.
=> chore: fix onboarding styles, sidebar fixes

apps/app/components/daydream/WelcomeScreen/Personas.tsx, packages/design-system/styles/globals.css
- Better animated border button (for personas and for "see more dreamscapes" future button)
https://github.com/user-attachments/assets/3b130ec5-b55c-4448-a147-a52904cac7c2
=> dd: feat: animated border button

apps/app/app/api/streams/upsert.ts, apps/app/components/welcome/featured/useDreamshaper.tsx
- Save whip_url in stream object
=> dd: feat: store whip url

apps/app/components/welcome/featured/dreamshaper.tsx
- Expand screen
- Prompt 
- Edit Prompt
- Adjustements
=> dd: feat: add tooltips

apps/app/components/welcome/featured/ManagedBroadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx
- Remove player overlay that is impeding to show controls on hover
- It was added back when the broadcast player was draggable, to avoid unwanted interactions
- Added fullscreen button
- Changed prompt icon to wand sparkles
=> dd: feat: player updates

apps/app/components/sidebar.tsx, packages/design-system/styles/globals.css
Technically making it white to match the background
=> Make sidebar transparent

apps/app/app/api/metrics/kafka.ts, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/components/welcome/featured/videojs-player.tsx, apps/app/components/welcome/featured/videojs-whep-plugin.d.ts, apps/app/hooks/useFallbackDetection.ts, apps/app/lib/track.ts, apps/app/package.json, pnpm-lock.yaml
Uses videojs player instead of the Livepeer Player
This is to debug gray screen issues having with playing back from mediamtx
=> dd: feat: videojs player fallback

apps/app/components/welcome/featured/useDreamshaper.tsx
- Use new whip server if admin
=> dd: feat: conditional whip server

apps/app/app/api/metrics/beacon/route.ts, apps/app/components/welcome/featured/dreamshaper.tsx
- unload event
- page leave event (commented out for now)
=> dd: feat: page leave events

apps/app/components/daydream/MainExperience/DaydreamContent.tsx, apps/app/components/daydream/MainExperience/index.tsx, apps/app/components/daydream/OnboardContext.tsx, apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/SelectPrompt.tsx, apps/app/components/daydream/index.tsx, apps/app/components/header/action.ts, apps/app/components/header/user.tsx, apps/app/next.config.mjs
- Old users directly jumping to main view now
- New user will go through onboarding only once
- Add personas to the Users Table in the DB
=> feat: fix onboarding flows, old users directed to main view

apps/app/components/welcome/featured/dreamshaper.tsx
- Added visibility change event to make sure we're also tracking mobile app swapping
=> dd: feat: visibility change event

apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx
As requested by @hthillman in https://linear.app/livepeer/issue/ENG-2607/change-no-permissions-text
=> Link to support form instead of docs

apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/package.json, pnpm-lock.yaml
- Added custom ICE servers for `Player` and `Broadcast`
- Turned ICE gathering back on for `Broadcast`
=> feat: add custom ICE servers

apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/package.json, pnpm-lock.yaml
- bump @livepeer/react version to "^4.3.0"
=> chore: bump version

apps/app/package.json, pnpm-lock.yaml
=> chore: bump version livepeer/react

apps/app/components/playground/broadcast.tsx
=> fix: temp: remove mirrored broadcast

apps/app/components/welcome/featured/videojs-player.tsx
- Remove videojs app_send_stream_request event
=> dd: remove videojs init event

apps/app/components/playground/broadcast.tsx, apps/app/hooks/useDreamshaper.tsx
- Updated ICE servers for broadcast
=> feat: remove invalid ICE servers for broadcast

apps/app/components/sidebar.tsx, apps/app/components/welcome/featured/MainContent.tsx, apps/app/components/welcome/featured/Overlay.tsx, apps/app/hooks/useStreamStatus.ts, packages/design-system/styles/globals.css, packages/tailwind-config/config.ts
- Matches the figma designs for loading overlay screens
- Added shimmer text effect for status message
=> fix: loading overlay bg screen

apps/app/app/api/metrics/log/route.ts, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/components/welcome/featured/videojs-player.tsx, apps/app/hooks/useFallbackDetection.ts, apps/app/lib/analytics/event-middleware.ts
- Standard serialization for events
- Videojs fallback timeout to 12s from 10s
- app_player_fallback_to_videojs event
=> dd: feat: standard event serialization

apps/app/components/stream/stream-debug-panel.tsx, apps/app/lib/utils.ts
- Fixed admin check
- Incapsulated in helper
- Added missing status so that the status in the debug panel is not anymore displayed as just "unknown"
=> dd: fix: debug panel admin + helper

apps/app/components/daydream/LoginScreen/EmailLoginButton.tsx
- Added `data-testid`s for e2e testing
=> test: add test ids

apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/Header.tsx
- Fixed broken layout on mobile
=> fix: make min-width responsive

apps/app/components/playground/broadcast.tsx
- Enable audio back
- Send it for 1 second, then mute
=> dd: feat: enable audio back

apps/app/app/explore/BentoGrids.tsx
This is to make the page look better on larger screens
=> Set a max width for /explore page

apps/app/components/welcome/featured/InputPrompt.tsx, apps/app/components/welcome/featured/prompt-settings.tsx
- Real-time updating param sliders
=> dd: feat: real-time params

apps/app/app/explore/BentoGrids.tsx, apps/app/app/explore/NoMoreClipsFooter.tsx, apps/app/app/explore/OptimizedVideo.tsx, apps/app/app/explore/VideoProvider.tsx
- Footer
- Fix for videos without moov atom, which was crashing on seek, now it just doesn't seek
=> dd: feat: no more clips footer

apps/app/app/explore/BentoGrids.tsx
- Fix background clouds to top of page
- Stretch vertically
- Stretch a little horizontally
- Remove rotation
- Increase opacity
=> Bigger fixed clouds

apps/app/app/explore/BentoGrids.tsx, apps/app/app/explore/NoMoreClipsFooter.tsx
This makes it match the text next to it
=> Fix daydream name font heights

apps/app/app/explore/BentoGrids.tsx
=> Lowercase words in header

apps/app/components/welcome/featured/Overlay.tsx, apps/app/components/welcome/featured/player.tsx
https://github.com/user-attachments/assets/68057110-25df-4c0c-a4a8-2fb8079ddf38
=> dd: feat: loading animation on player

apps/app/components/daydream/WelcomeScreen/index.tsx
=> dd: feat: blur on onboarding background

apps/app/app/(main)/QuickviewVideo.tsx
- Remove italic and put it 70% of width
=> dd: fix: prompt styling in explore page

apps/app/app/(main)/QuickviewVideo.tsx, apps/app/app/(main)/clips/[slug]/page.tsx, apps/app/components/header/index.tsx, apps/app/components/playground/try.tsx, apps/app/components/sidebar.tsx
- change links that are pointing '/explore' to '/'
=> fix: change old explore links

apps/app/app/admin/clips/components/EditClipModal.tsx, apps/app/app/api/admin/clips/update/route.ts
This is needed for the clip creation to work
Address the need for an id and a slug on newly created clips
=> dd: fix: fix admin page with slug and clip id

apps/app/app/(main)/PlayButton.tsx, apps/app/app/(main)/QuickviewVideo.tsx, apps/app/app/(main)/Slider.tsx, apps/app/app/(main)/VideoPlayer.tsx
- Rework slider
- Rework header
- Rework slider interaction
=> dd: feat: new preview quick video

apps/app/app/(main)/OptimizedVideo.tsx
Falling back to non short clip if the short clip does not exist
=> dd: feat: fallback to non-short clip

apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/NoMoreClipsFooter.tsx
I put the logo into a circle just to check if it was centered, and it was! moved it 2 pixels on the right
also, copy changes
=> dd: fix: copy & footer fixes

apps/app/app/(main)/Header.tsx, apps/app/app/(main)/QuickviewVideo.tsx
- Create button in the preview page
- Increase padding on it, and on the header button
=> dd: feat: create button in clip preview

apps/app/app/(main)/BentoGrids.tsx
Remove name/title components for videos
=> feat: remove components

apps/app/app/(main)/OptimizedVideo.tsx
=> feat: display first frame on mobile

apps/app/drizzle/0003_wandering_bedlam.sql, apps/app/drizzle/meta/0003_snapshot.json, apps/app/drizzle/meta/_journal.json, apps/app/lib/db/schema.ts
Added migrations for production database compatibility.
=> feat: change column defs for production

apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/hooks/useClipsFetcher.ts, apps/app/app/(main)/layout.tsx, apps/app/app/(main)/page.tsx
=> dd: fix: fetch via api also initial clips

apps/app-e2e/tests/video.dev.spec.ts, apps/app-e2e/tests/video.spec.ts
`page.goto("/")` -> `page.goto("/create")`
=> fix: update e2e test url

apps/app/components/welcome/featured/Header.tsx, packages/design-system/styles/globals.css
- Back to explore button
- Remove logo + subtitle
- Join community on top right
- Explore icon for mobile
=> dd: feat: back to explore button

apps/app/components/playground/broadcast.tsx
This reverts commit c12f47304c711494b8ecef2861376aec061fa263.
=> Revert "dd: feat: enable audio back (#371)"

apps/app-e2e/playwright.config.ts, apps/app-e2e/tests/video.spec.ts
- Longer timeout for auth elements visibility
- Save screenshots on errors
=> test: change test configurations

apps/app/app/(main)/MainLayoutClient.tsx, apps/app/app/(main)/layout.tsx, apps/app/app/(main)/page.tsx, apps/app/app/api/clips/route.ts, apps/app/drizzle/0005_dear_siren.sql, apps/app/drizzle/meta/0005_snapshot.json, apps/app/drizzle/meta/_journal.json, apps/app/lib/db/schema.ts
- Added approval fields to `clips` table
- `approval_status`: `enum("none", "pending", "approved", "rejected")`
- `approved_by`
- `approved_at`
=> feat: add approval fields

apps/app/drizzle/0006_dry_psynapse.sql, apps/app/drizzle/meta/0006_snapshot.json, apps/app/drizzle/meta/_journal.json, apps/app/lib/db/schema.ts
- Added `streams_stream_key_idx`
```sql 
CREATE INDEX "streams_stream_key_idx" ON "streams" USING hash ("stream_key");
```
=> feat: add index on streams table

apps/app/(main)/QuickviewVideo.tsx, apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/OptimizedVideo.tsx, apps/app/app/(main)/QuickviewVideo.tsx, apps/app/app/create/page.tsx, apps/app/components/ClipButton.tsx, apps/app/components/ClipModal.tsx, apps/app/components/daydream/MainExperience/index.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/index.tsx, apps/app/components/daydream/index.tsx, apps/app/components/guest/GuestSignupModal.tsx, apps/app/components/welcome/featured/BentoGridOverlay.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/Header.tsx, apps/app/components/welcome/featured/InputPrompt.tsx, apps/app/components/welcome/featured/MainContent.tsx, apps/app/components/welcome/featured/OverlayClipViewer.tsx, apps/app/hooks/useGuestUser.ts, apps/app/hooks/useOverlayStore.ts, apps/app/hooks/useTrialTimer.ts, apps/app/lib/clipStorage.ts
- Allow access to the main experience as guest if coming from "Try this prompt"
- Set up limits for guests (5 prompts, no share, no clip download)
- Set up indexDB storage for temp clips, so when you then sign-up you can recover your pending clip
- Rework of clip created modal
- Rework of Try this prompt buttons
- Guest user hook and store
- Explore overlay mode for never ending prompt cloning
=> [wip]: feat: guest mode + never ending prompt cloning

apps/app/app/(main)/OptimizedVideo.tsx
HEAD request is failing due to CORS
=> dd: fix: short clips fallback

apps/app/components/GradientAvatar.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/index.tsx, apps/app/components/modals/unified-signup-modal.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/TutorialVideo.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/package.json, packages/design-system/styles/globals.css, pnpm-lock.yaml
- Guest already tried the experience, so they need to skip camera access + prompt selector
- Different copy
- Added display name input
- Added avatar selector (randomized for now until feedback)
- Random username generator
- Tutorial video for guests
=> dd: feat: guest onboarding + display name input and avatar + tutorial video

apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/hooks/useDreamshaper.tsx
- A fix for prompt overriding
- Wait for auth to be ready before checking if to display the sign up modal or not
=> dd: fix: prompt override

apps/app/components/welcome/featured/BentoGridOverlay.tsx
- Fetch 96 clips in creation mode since never ending scroll is not working correctly there
=> dd: fix: 96 clips in creation mode

apps/app/app/admin/clips/components/EditClipModal.tsx, apps/app/app/admin/clips/page.tsx, apps/app/app/admin/types.ts, apps/app/app/api/admin/clips/route.ts, apps/app/app/api/clips/route.ts, apps/app/components/daydream/Clipping/ClipSummaryContent.tsx
- Added toggle switch for `Submit to be featured` which sends the uploaded video into `pending` approval state.
- Added admin panel selector to change the status of the approval of clips between `none, pending, approved, rejected`
Switch Toggle:
Admin Approval Selector:
=> feat: allow user to publish clips to explore

apps/app/components/daydream/Clipping/ClipOptionsModal.tsx, apps/app/components/daydream/Clipping/ClipSummaryContent.tsx
- No radio button
- Less top card padding
- More general padding on the modal
- Less image height in the card
- Align shadow with the shadow in the designs
=> dd: fix: clip modal

apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/hooks/useDreamshaper.tsx
NOTE: This is using production as base
=> dd: hotfix: input prompt override prod hotfix

apps/app/app/admin/tools/clip-approval-queue/page.tsx, apps/app/app/admin/tools/page.tsx, apps/app/components/daydream/Clipping/ClipButton.tsx, apps/app/components/daydream/Clipping/ClipModal.tsx, apps/app/components/daydream/Clipping/ClipOptionsModal.tsx, apps/app/components/daydream/Clipping/ClipShareContent.tsx, apps/app/components/daydream/Clipping/ClipSummaryContent.tsx, apps/app/components/daydream/Clipping/types.ts, apps/app/hooks/useVideoClip.ts
- Store prompt as well with the clip
- Create the correct share url using the slug id
- Fix layout of clip intermediate modal that was overflowing on smaller screens
- Store thumbnail as well
- Clip Approval Queue admin page
=> dd: feat: store prompt, thumbnail, slug in clips + admin uploaded clips mgmt

apps/app/app/actions/user.ts, apps/app/components/daydream/OnboardContext.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/index.tsx, apps/app/components/modals/unified-signup-modal.tsx
- Display error when a user enters a display name and submits it. 
- Updated Guest user handling fixes to disable Continue when fields are empty or invalid
- Fix CSS for Join Community Button
=> feat: throw error on already used usernames

apps/app/components/sidebar.tsx
Same hotfix done in production here https://github.com/livepeer/pipelines/pull/466
=> dd: fix: sidebar link

apps/app/app/admin/tools/clip-approval-queue/page.tsx
- Display name of clip uploader in approval queue
- Fix white flickering on hover
=> dd: admin: display uploader name in approval queue

apps/app/app/(main)/Header.tsx, apps/app/components/welcome/featured/Header.tsx, apps/app/components/welcome/featured/Overlay.tsx
Rationale
We've got to tell users we're in beta and give them a way to offer feedback! Also, cycling interesting loading messages makes the wait time go a lot faster.
Testing notes
I've tested chrome/safari/brave on desktop and mobile. Need more mobile devices please!
=> Beta tag + a few more goodies

apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/Header.tsx, apps/app/app/(main)/MainLayoutClient.tsx, apps/app/app/(main)/OptimizedVideo.tsx, apps/app/app/(main)/QuickviewVideo.tsx, apps/app/app/api/capacity-notification/route.ts, apps/app/components/daydream/MainExperience/index.tsx, apps/app/components/modals/capacity-notification-modal.tsx, apps/app/components/modals/capacity-toast.tsx, apps/app/components/welcome/featured/CapacityOverlay.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/Overlay.tsx, apps/app/components/welcome/featured/PlayerOverlay.tsx, apps/app/hooks/useCapacityCheck.ts, apps/app/hooks/useCapacityToast.ts, apps/app/hooks/useDreamshaper.tsx, apps/app/lib/analytics/hubspot.ts, apps/app/lib/env.ts, packages/design-system/styles/globals.css
- Added a capacity check via infra api
- Added a capacity toast for the explore page
- Capacity walls on try prompt, create
- Added capacity modal for submitting email
- Added capacity overlay for walling on the creation page
- Refactor the capacityMonitor, now errorMonitor, to use the overlay as double tool for capacity and error displays
=> dd: feat: capacity-check

apps/app/app/(main)/OptimizedVideo.tsx, apps/app/app/(main)/QuickviewVideo.tsx, apps/app/components/footer/stream-info.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/InputPrompt.tsx, apps/app/components/welcome/featured/MobileInputPrompt.tsx, apps/app/components/welcome/featured/ResponsiveInputPrompt.tsx, apps/app/hooks/useCapacityCheck.ts
- Split the input prompt in 2 components, mobile and desktop
- Fix caret position
- Fix textarea auto-expand and padding
- Fix parameters adding
- Added param slider to mobile as well
- Fixed pencil icon shrinking on long prompts
- Moved vdev copy button right beside the debug panel, so it doesn't overlay stuff
=> dd: feat: fix input prompt

apps/app/app/(main)/VideoProvider.tsx, apps/app/app/admin/tools/clip-approval-queue/page.tsx, apps/app/components/daydream/Clipping/ClipButton.tsx, apps/app/components/daydream/Clipping/ClipModal.tsx, apps/app/components/daydream/Clipping/ClipOptionsModal.tsx, apps/app/components/daydream/Clipping/ClipSummaryContent.tsx, apps/app/components/daydream/Clipping/types.ts, apps/app/hooks/useVideoClip.ts
- Vertical mode for clips
- Refactor modals to get the vertical option as well
- Refactor preview modal
- Fix quick preview for vertical clips
- Fix admin preview for vertical clips
=> dd: feat: clip vertical recording mode

apps/app-e2e/tests/video.dev.spec.ts, apps/app-e2e/tests/video.spec.ts
- `test.info().titlePath.join(" > ")` -> `test.info().title`
=> test: make test names more concise

.github/workflows/e2e-monitor.yml
Update cron schedule to be just 5 minutes
=> Set trigger condition for E2E dynamically

apps/app/components/daydream/LoginScreen/EmailLoginButton.tsx
To help us debug the ongoing issues some people are having with logging in and also to get a sense of how widespread it is
=> Add tracking event for login email errors

apps/app/components/daydream/LoginScreen/EmailLoginButton.tsx
```typescript
const handleLogin = async (e: React.FormEvent<HTMLFormElement>) => {
track("daydream_login_email_clicked");
try {
await sendCode({ email });
} catch (error) {
// Added this line
track("daydream_login_email_error", {
error: error instanceof Error ? error.message : "Unknown error",
});
}
};
```
=> feat: track email login failure

apps/app/app/(main)/OptimizedVideo.tsx
=> feat: pin tutorial button and update design

apps/app-e2e/tests/video.spec.ts
- Lower variance threshold to `4000`
=> test: lower variance threshold

apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/Header.tsx, apps/app/components/daydream/index.tsx
Reverts livepeer/pipelines#520
=> Revert "CTAs in place of subhead"

.github/workflows/pr-agent.yml, apps/app/app/(main)/VideoProvider.tsx, apps/app/app/admin/tools/clip-approval-queue/page.tsx, apps/app/components/daydream/Clipping/ClipButton.tsx, apps/app/components/daydream/Clipping/ClipModal.tsx, apps/app/components/daydream/Clipping/ClipOptionsModal.tsx, apps/app/components/daydream/Clipping/ClipSummaryContent.tsx, apps/app/components/daydream/Clipping/GuestModeContent.tsx, apps/app/components/daydream/Clipping/types.ts, apps/app/components/daydream/index.tsx, apps/app/hooks/useVideoClip.ts, apps/app/lib/clipStorage.ts
=> feat: add vertical clip recording mode

apps/app/package.json
- `db:push`: to push schema changes to db
- `db:generate`: to generate migrations from schema changes
=> feat: add db commands to package.json
