livepeer/pipelines

apps/app/app/api/streams/webhook/route.ts
I realised after playing around with the API that you're already using `stream_key` elsewhere so it makes sense to go back to how you had it to be consistent 👍
=> Switch back to stream_key for webhook param name

apps/docs/technical/develop-pipeline/add-sd-loras.mdx
Updates the hugging-face repositories for checkpoints to:
LoRa checkpoints
[Livepeer-Studio/comfystream_loras](https://huggingface.co/Livepeer-Studio/comfystream_loras/tree/main)
SD 1.5 model checkpoints
[Livepeer-Studio/comfystream_checkpoints](https://huggingface.co/Livepeer-Studio/comfystream_checkpoints/tree/main)
=> (docs) update hugging-face repo url for checkpoints

apps/docs/technical/develop-pipeline/local-testing.mdx, apps/docs/technical/reference/tunneling-with-ssh.mdx
- Fix typo in linux install steps for custom nodes
- Update port for ComfyStream to use 8889 instead of 8888 for both linux/windows to improve consistency and avoid conflicts with juptyer lab on RunPod
=> Fix linux step typo, update ports

apps/app/components/playground/player.tsx
Related lvpr.tv change: https://github.com/livepeer/ui-kit/pull/585
=> Improve startup time by changing the backoffMax from `30s` (default) to `1s`

apps/app/components/playground/broadcast.tsx
For audio passthru to work, the player needs to load with mic enabled by default.
=> broadcast: enable mic input by default

apps/app/components/daydream/index.tsx, apps/app/components/welcome/featured/interstitial.tsx
This is s rework of how camera and mic permission are working
How it was before:
- Onload, check if user has given permission for camera and mic. If he hasn't, instantly prompt them. If they have already, close the interstitial
Now:
- Onload, check if the user has given permission for camera and mic. if he hasn't display the permissions modal. if the user clicks, prompts for permissions, then show the prompt selector.
=> ui: daydream: camera permission rework

apps/app/components/daydream/index.tsx, apps/app/components/stream/stream-debug-panel.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
- Adding admin debug panel for daydream
Open issues:
- The payload is static, would be good to have that JSON editable and a button "Apply" to send its parameters to the control api. Maybe even display the parameter in a separate editable container for clarity
=> ui: landing: debug panel

apps/app/app/api/streams/delete.ts, apps/app/app/api/streams/get.ts, apps/app/app/api/streams/upsert.ts, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/lib/core.ts
Uses the Livepeer Player component to render the playback.
- Supports mediamtx playback by default
- Support livepeer tv playback: Set the env variable `NEXT_PUBLIC_LIVEPEER_DIRECT_PLAYBACK=true` and rebuild
- Add logic to track Time-To-First-Frame: add `debugMode=true` to query params to view this
Ex: https://pipelines-gd548c8e2-livepeer.vercel.app/?debugMode=true
- Added tracking event `stream_first_frame_loaded` to track the time taken to load first frame
=> feat: use Livepeer Player instead of iframe for daydream

apps/app/components/welcome/featured/useDreamshaper.tsx
So, what is happening is that the page load before the privy auth completes, so it creates a stream with the default infraservice user
But then, when privy completes, the user get updated and since user is in the dependencies of the stream creation, another stream gets created 
This causes instabilities sometimes with the status fetch, since depending on DB speed it's fetching the previous stream, and it's also sometime broadcasting on the first stream for a while before privy gets ready
This addresses the issue, waiting for the privy ready state to be true before doing any action
=> daydream: fix: stream creation render

packages/design-system/providers/privy.tsx
- Add env var `NEXT_PUBLIC_PRIVY_APP_ID` to point to separate prod and staging envs separately.
- Added env vars to vercel
=> chore: fix privy app id always pointed to prod

apps/app/components/welcome/featured/dreamshaper.tsx, apps/app/components/welcome/featured/player.tsx
- Added back the status messages loading screen
- Added a fallback to use iframe based player using `NEXT_PUBLIC_IFRAME_PLAYER_FALLBACK='true'`. defaulted to false to use react player.
=> chore: add loading screen, iframe fallback

apps/app/components/daydream/index.tsx
- `handleReady` handler resets the states only if the stream is not killed.
=> feat: trigger handleReady conditionally

apps/app/components/welcome/featured/ManagedBroadcast.tsx, apps/app/components/welcome/featured/dreamshaper.tsx
So, this was kind of a mess
Mobile and desktop were using 2 separate broadcast components, and this was causing reconnection issues, because on resize under 768px of width, it would destroy the currently running broadcast and recreate it, effectively interrupting the stream and freezing the app
This was also affecting mobile landscape mode, as broadcast recreation was interrupting the stream in that case too
What I did is:
- Unify the broadcasts to use a single component
- Make sure styling is correct for both mobile and desktop - had some hard time here because on desktop the broadcast was living with the output player as parent and on mobile was living outside of it, so I needed to reposition the broadcast correctly on desktop
- Move everything in a separate component for clarity
This …
=> fix: dd: single broadcast player component

apps/app/app/page.tsx, apps/app/components/daydream/LoginScreen/AuthContext.tsx, apps/app/components/daydream/LoginScreen/DiscordLoginButton.tsx, apps/app/components/daydream/LoginScreen/EmailLoginButton.tsx, apps/app/components/daydream/LoginScreen/GoogleLoginButton.tsx, apps/app/components/daydream/LoginScreen/index.tsx, apps/app/components/daydream/index.tsx
When user logged in using OAuth providers i.e. Google or Discord, we were seeing the login screen for a split second on redirect. This is due to Privy provider taking a bit of time to validate the authentication. 
- Moved the OAuth Initialization to the top of the components so that we can verify the oauthstate and if the user has successfully auth, if so we display a loader for the time until privy authenticates the user.
=> chore: fix oauth redirect issue

apps/app/components/sidebar.tsx
Eric asked to remove the Discord link as it's duplication of the one at the top of the page. He also said the other two aren't needed.
=> Remove sidebar Discord Community, Feedback and Documentation links

apps/app/components/daydream/LoginScreen/index.tsx
This should independent of any changes to the wording on the button in the future
=> Change 'By clicking continue' to 'By signing up'

apps/app/package.json, packages/design-system/package.json, packages/design-system/providers/index.tsx, packages/next-config/package.json, pnpm-lock.yaml
Reverted back the vercel toolbar on request from Hunter.
=> fix: Revert vercel toolbar back to pre-prod envs

apps/app/components/daydream/SystemStatus.tsx, apps/app/components/sidebar.tsx, apps/app/hooks/useSystemStatus.ts
- Added a button on the sidebar to navigate to the status endpoint.
- Added a hook to fetch the systems operational status and display an indicator on the icon
=> chore: add system status to daydream

apps/app/app/actions/user.ts, apps/app/components/daydream/OnboardContext.tsx, apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/SelectPrompt.tsx, apps/app/components/daydream/index.tsx
- Added a server action to create and update user table data with the following schema. `additional_details` is already an existing field in the Users table, we are reusing it.
```
additional_details: {
next_onboarding_step: "persona" | "camera" | "prompt" | "main",
personas: [],
customPersona: ""
}
```
- Updated the onboarding logic to move to DB persisted step instead of local storage, now the user will login into the exact onboarding step they left off at, even on other devices.
=> feat: Add DB persistence to onboarding steps

apps/app/components/daydream/OnboardContext.tsx, apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/components/daydream/WelcomeScreen/Personas.tsx, apps/app/components/daydream/WelcomeScreen/SelectPrompt.tsx, apps/app/components/daydream/index.tsx
- Highlighted personas were lost on refresh, now persisted from DB
- Padding of the title in prompt selection view - added more padding.
- Moved tracking to after user initialization processing to display onboarding faster to the user.
=> chore: Fix selected personas lost after refresh, prompt styles

apps/app/lib/analytics/mixpanel.ts
Added Google, Discord emails to be passed down to mixpanel when user signs in using Oauth.
=> fix: add oauth email for mixpanel events

apps/app/components/daydream/LoginScreen/index.tsx, apps/app/components/footer/stream-info.tsx
- Adjusted the shadow container width and styles to match the placeholder video and prevent overflow shadows on mobile, small and large screens.
- Moved the debug info position to access copy button easily
before:
after:
=> fix: shadow container on login screen

apps/app/app/api/metrics/beacon/route.ts, apps/app/app/api/metrics/log/route.ts, apps/app/components/daydream/WelcomeScreen/CameraAccess.tsx, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/Overlay.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/components/welcome/featured/videojs-player.tsx, apps/app/hooks/useFallbackDetection.ts, apps/app/lib/analytics/event-middleware.ts, apps/app/lib/utils.ts
- When user resets camera, the camera access button in onboarding was showing checked. Fixed it now based on permission granted.
- Previously when a user camera was unavailable the Broadcast component would automatically request for the camera. This resulted in permissions being asked even before entering the main experience. This PR fixes that by disallowing Broadcast video if camera permissions are not granted.
- Also fixed formatting in a bunch of files.
=> fix: camera permission issues when user resets camera manually

apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/Header.tsx, apps/app/hooks/useMobileStore.ts
- Previously on short screen or in landscape mode, the action buttons were cluttering the screen. Now wrapping them to below the title.
=> fix: action icons header to wrap

apps/app/app/explore/BentoGrids.tsx
=> Hand pointer for mousing over explore page items

apps/app/app/explore/BentoGrids.tsx, apps/app/app/explore/OptimizedVideo.tsx, apps/app/app/explore/QuickviewVideo.tsx, apps/app/app/explore/VideoPlayer.tsx, apps/app/app/explore/VideoProvider.tsx, apps/app/hooks/usePreviewStore.ts, packages/design-system/styles/globals.css
- Animated loading background
- Same animation for preview
- Bigger preview playback
- Increased threshold for video cleanup
- Freeze Bento videos when preview is opened
<video src="https://github.com/user-attachments/assets/8cd25163-8b4c-4cb1-a4db-6edd96f240db" controls width="600"></video>
<video src="https://github.com/user-attachments/assets/2fdf12b2-4876-495e-9cc1-3f537034bad4" controls width="600"></video>
=> dd: feat: animated bento grid on loading + bento grid updates

apps/app/app/admin/clips/page.tsx, apps/app/app/api/admin/clips/route.ts, apps/app/app/api/clips/route.ts, apps/app/app/explore/BentoGrids.tsx, apps/app/app/explore/hooks/useClipsFetcher.ts, apps/app/app/explore/page.tsx
- Consider priority when displaying clips, both in admin and grid. The priority is the specified position in the grid or table
- Handle this for the pagination as well
- added a ?debug flag to the explore page that shows the index number of clips, useful when editing clip priorities
- Throw an error if you try to assign a priority number to a clip and that position is already occupied by another prioritized clip
- Handle priority gaps
=> dd: feat: clips priority for admin & bento grid

apps/app/components/daydream/WelcomeScreen/index.tsx
=> feat: change subheader

apps/app/components/daydream/LoginScreen/index.tsx
=> fix: fix broken login layout

apps/app/app/(main)/hooks/useClipsFetcher.ts, apps/app/app/api/clips/route.ts, apps/app/app/api/metrics/beacon/route.ts, apps/app/app/api/metrics/log/route.ts, apps/app/components/playground/broadcast.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx, apps/app/components/welcome/featured/Header.tsx, apps/app/components/welcome/featured/InputPrompt.tsx, apps/app/components/welcome/featured/Overlay.tsx, apps/app/components/welcome/featured/player.tsx, apps/app/components/welcome/featured/videojs-player.tsx, apps/app/hooks/useFallbackDetection.ts, apps/app/lib/analytics/event-middleware.ts, apps/app/lib/utils.ts
Now that we reverted player and broadcast related stuff, this PR:
- Re run pnpm format since some formatting was reverted
- Restore CSS-only changes on the loading player
- Make "back to explore" a button
- Add radius to header buttons
- Change the background of the video tag and the input prompt to fefefe  as designs
- Fix a situation where the prompt wasn't getting sent to the bento grid "Try this prompt" button
=> dd: feat: prettier + restore css changes + better buttons

apps/app/app/(main)/OptimizedVideo.tsx
- Due to threshold set to 90% it looked like the top fold videos were not autoplaying, by setting the threshold to 50%, we can now see that the videos are working as expected.
https://github.com/user-attachments/assets/97c0d5e8-7c5d-48b6-a30c-07fc0584ba50
=> fix: autoplay videos threshold to 50%

apps/app/components/daydream/Clipping/ClipShareContent.tsx
- Added functionality to share to socials for Instgram, X and Tiktok.
- For apps like IG, Tiktok - there is no direct way to share to the app, hence we follow a web based sharing option and fallback to open the url in the browser by showing a toast to the User that the link has been copied. This approach is used in other apps too.
=> feat: add IG, Tiktok, X Share options

apps/app/components/daydream/index.tsx
IsGuestMode was persisted in localStorage via Zustand's persist middleware, but there was no code that explicitly resetted this value when a user logs in - now this is fixed and fixing a edge case where logged in users would see the tutorial video or the sign up CTA modal after coming from a previous guest session
Note: very rare bug outside of development / internal sessions
=> dd: fix: fix persistent guest store

apps/app/components/footer/stream-info.tsx, apps/app/components/stream/stream-debug-panel.tsx, apps/app/components/welcome/featured/Dreamshaper.tsx
This was driving me nuts - moved the version copy to center, so it's more easily accessible
=> Fix version number padding

apps/app/app/(main)/OptimizedVideo.tsx, apps/app/components/daydream/index.tsx
Fixing a potential bug introduced here https://github.com/livepeer/pipelines/pull/467
where guestMode was set as false because of unready privy auth
=> dd: fix: wait for auth for guest mode

apps/app/components/playground/broadcast.tsx
Users were unclear on if they were broadcasting to an audience
=> Change broadcast window 'Live' to 'Active' to be less confusing to users

apps/app/components/welcome/featured/useValidateInput.tsx
- Previously MAX_PROMPT_LENGTH was set to 490 chars, but we are seeing some errors now due to it causing stream failures. Reset it to 300 chars to allow the user to prevent sending it in the first place by adding client side validation.
Test Prompt From Bug Report:
```
Realistic women with black scary armor, Holding fire Sword,human face,long hair, perfectly detailed on dragon armors,Super detail face,high details on face,realistic face, character highly detailed, character sheets, Detailed, sharp focus, Super detailed full body, 32k resolution, Only a reality graphic,epic background,epic pose,horror,high resolution,Resonance,fire and ash background --quality 3)
```
=> fix: max prompt length reduced to prevent stream errors

apps/app-e2e/tests/common.ts, apps/app-e2e/tests/video.dev.spec.ts, apps/app-e2e/tests/video.spec.ts
The selection is done if there exists a `WHIP_REGIONS` environment variable, which is a comma-separated list of endpoints.
There is also an additional 49% chance that whip selection will not happen and the E2E tests will continue with defaults.
=> e2e-test: Add dynamic selection of WHIP endpoint during E2E

apps/app/app/api/clips/presigned-thumbnail/route.ts, apps/app/app/api/clips/presigned-upload/route.ts, apps/app/app/api/clips/route.ts, apps/app/components/daydream/Clipping/ClipSummaryContent.tsx, apps/app/hooks/useVideoClip.ts, apps/app/lib/storage/gcp.ts
We were previously hitting a Vercel API limit where request > 4.5Mb gets rejected.
The API now returns a presigned GCP URL and the frontend uploads directly there.
=> Upload clips + thumbnails via Presigned URLs. Remove size check. Increase max length to 60s.

apps/app/components/welcome/featured/Header.tsx
=> Mobile: 'More prompts' as text rather than search icon

apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/NoMoreClipsFooter.tsx
- On the Overlay Mode we see that the Create CTA is pointing towards the /create page on which the user is already present. Hence we see a no-op in this case. 
- Updated the functionality to close the overlay in such cases and changes the copy to "Continue Creating" instead of "Create" in overlay mode.
https://github.com/user-attachments/assets/c346e6a9-c8f4-4c7f-b56f-743227240f8f
=> fix: create CTA in NoMoreClipsFooter Button

apps/app/app/(main)/BentoGrids.tsx, apps/app/app/(main)/OptimizedVideo.tsx, apps/app/app/(main)/QuickviewVideo.tsx, apps/app/app/(main)/clips/[slug]/page.tsx, apps/app/app/(main)/hooks/useClipsFetcher.ts, apps/app/app/(main)/layout.tsx, apps/app/app/admin/clips/components/EditClipModal.tsx, apps/app/app/admin/clips/page.tsx, apps/app/app/admin/types.ts, apps/app/app/api/admin/clips/route.ts, apps/app/app/api/clips/[id]/route.ts, apps/app/app/api/clips/route.ts, apps/app/drizzle/0008_loud_lockjaw.sql, apps/app/drizzle/meta/0008_snapshot.json, apps/app/drizzle/meta/_journal.json, apps/app/lib/db/schema.ts
- Added `is_tutorial` column to the clips DB table
- Added support to update the flag from admin panel
- Updated the CTA action for tutorial clips and removed the CTA from /clips/<slug> page for such clips
- Added support to copy footer prompt directly by a single click.
https://github.com/user-attachments/assets/ab52696c-53ef-4d42-9957-70f8928ffc4f
=> feat: add is_tutorial support for clips

apps/app/hooks/useCapacityCheck.ts
There are currently issues with the reported capacity and machines that are reporting having capacity when broken. 
Because of this, we err on the side of caution and check if we're over 80% of capacity before returning false.
=> Throw capacity errors once we're at 80% of capacity

apps/app/lib/clipStorage.ts
- `storeClip` and `retrieveClip` now use `arrayBuffer` instead of `blob` for Safari compatibility
=> feat: store clips as arraybuffer in indexedDB

apps/app/app/(main)/Header.tsx, apps/app/components/header/index.tsx, apps/app/components/modals/capacity-notification-modal.tsx, apps/app/components/modals/trial-expired-modal.tsx, apps/app/components/modals/unified-signup-modal.tsx, apps/app/components/welcome/featured/Header.tsx, apps/app/components/welcome/featured/PlayerOverlay.tsx, apps/app/components/welcome/featured/index.tsx, apps/app/components/welcome/index.tsx
We no longer want to direct people to the regular Livepeer Discord 
Context: https://discord.com/channels/423160867534929930/1369370282988408904/1369370286323011624
=> Change Discord link to new Daydream-specific one

apps/app/package.json
For issues like those addressed in #584, `build:ci` was added. `build` no longer includes `db:push`.
=> feat: add `build:ci` script

apps/app/components/playground/broadcast.tsx
- Re-enabled `noICEGathering`  flag in `Broadcast`, since this check in `ui-kit` does not seem to affect anything.
- **This is a temporary fix**
```ts
async function waitToCompleteICEGathering(peerConnection: RTCPeerConnection) {
return new Promise<RTCSessionDescription | null>((resolve) => {
/** Wait at most five seconds for ICE gathering. */
setTimeout(() => {
resolve(peerConnection.localDescription);
}, 5000);
peerConnection.onicegatheringstatechange = (_ev) => {
if (peerConnection.iceGatheringState === "complete") {
resolve(peerConnection.localDescription);
}
};
});
}
```
Potential changes:
```ts
async function waitToCompleteICEGathering(peerConnection: RTCPeerConnection) {
return new Promise<RTCSessionDescription | null>((resolve) => {
const originalHandler = …
```
=> perf: enable noICEGathering flag

apps/app/app/api/admin/clips/route.ts, apps/app/app/api/admin/clips/update/route.ts
Bug:
Sometimes setting a field (e.g Priority) using the Admin page, we'd get a 200 back for the PUT request, with the response saying "Clip updated successfully" and containing a clip JSON with the updated priority. In the database though, the update wasn't persisted
=> Order admin page in same way as site. Try to fix issue with Admin updates not persisting to DB.

apps/app/components/home/PromptDisplay.tsx
This fixes an issue where we were only showing the oldest 3 prompts on mobile rather than the most recent 3.
Remaining issue of a submitted prompt disappearing until it becomes active will be resolved in a followup PR.
=> Fix prompt list only showing oldest prompts on mobile

apps/app-e2e/playwright.config.ts
Retries were making debugging a little tricky because the screenshots would be overwritten if a retry passed so disable for now
=> Disable e2e retries for now
